version: "3.7"
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front
    working_dir: /front/react-typescript-weather-app
    tty: true
