FROM python:3.11-slim-bullseye

COPY ./server /app

WORKDIR /app

RUN pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]